/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.11
 * Generated at: 2025-10-18 18:42:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.docgia;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class newsletter_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1760802865264L));
    _jspx_dependants.put("jar:file:/H:/web_abcnew_asignment/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/abc_new/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fmt.tld", Long.valueOf(1664428278000L));
    _jspx_dependants.put("jar:file:/H:/web_abcnew_asignment/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/abc_new/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664428278000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Đăng ký Newsletter - ABC News</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/docgia.css\">\r\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/favicon.ico\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Header Top Bar -->\r\n");
      out.write("    <div class=\"header-top\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"header-top-content\">\r\n");
      out.write("                <div class=\"header-date\">\r\n");
      out.write("                    <span id=\"currentDate\"></span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"header-tools\">\r\n");
      out.write("                    <a href=\"#\" title=\"RSS\">📡 RSS</a>\r\n");
      out.write("                    <a href=\"#\" title=\"Mobile\">📱 Mobile</a>\r\n");
      out.write("                    <a href=\"#\" title=\"Ứng dụng\">📲 App</a>\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/docgia/newsletter.jsp\" title=\"Newsletter\" class=\"active\">📧 Newsletter</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Main Header -->\r\n");
      out.write("    <header class=\"header\">\r\n");
      out.write("        <div class=\"header-main\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"header-content\">\r\n");
      out.write("                    <div class=\"logo\">\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/docgia/index.jsp\">\r\n");
      out.write("                            <h1>ABC NEWS</h1>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"logo-tagline\">Tin nhanh - Chính xác - Cập nhật 24/7</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"header-right\">\r\n");
      out.write("                        <form class=\"search-form\" action=\"search.jsp\" method=\"get\">\r\n");
      out.write("                            <input type=\"text\" name=\"q\" placeholder=\"Tìm kiếm tin tức...\" required>\r\n");
      out.write("                            <button type=\"submit\">🔍</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"user-menu\">\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login.jsp\">Đăng nhập</a>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login.jsp\">Đăng ký</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <!-- Navigation Menu -->\r\n");
      out.write("    <nav class=\"navbar\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <ul class=\"nav-menu\">\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/docgia/index.jsp\">Trang chủ</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/docgia/category.jsp?id=3\">Thể thao</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/docgia/category.jsp?id=4\">Kinh tế</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/docgia/category.jsp?id=5\">Giải trí</a></li>\r\n");
      out.write("                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/docgia/category.jsp?id=6\">Công nghệ</a></li>\r\n");
      out.write("               \r\n");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <!-- Breadcrumb -->\r\n");
      out.write("    <div class=\"container\" style=\"margin: 15px auto;\">\r\n");
      out.write("        <nav style=\"font-size: 13px; color: #666;\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/docgia/index.jsp\" style=\"color: #c41e3a;\">Trang chủ</a> \r\n");
      out.write("            <span style=\"margin: 0 8px;\">›</span>\r\n");
      out.write("            <span>Newsletter</span>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Main Content -->\r\n");
      out.write("    <div class=\"main-wrapper\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"content-layout\">\r\n");
      out.write("                <!-- Main Content -->\r\n");
      out.write("                <main class=\"main-content\">\r\n");
      out.write("                    <!-- Newsletter Header -->\r\n");
      out.write("                    <div style=\"text-align: center; margin-bottom: 40px; padding: 40px 20px; background: linear-gradient(135deg, #c41e3a, #a01729); color: white; border-radius: 12px;\">\r\n");
      out.write("                        <div style=\"font-size: 4rem; margin-bottom: 20px;\">📧</div>\r\n");
      out.write("                        <h1 style=\"font-size: 2.5rem; margin-bottom: 15px; font-weight: bold;\">Newsletter ABC News</h1>\r\n");
      out.write("                        <p style=\"font-size: 1.2rem; opacity: 0.9; max-width: 600px; margin: 0 auto;\">\r\n");
      out.write("                            Nhận tin tức nóng hổi và chính xác nhất từ ABC News ngay trong hộp thư của bạn\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Success Message (if subscribed) -->\r\n");
      out.write("                    <div id=\"successMessage\" style=\"display: none; background: #d4edda; border: 1px solid #c3e6cb; color: #155724; padding: 20px; border-radius: 8px; margin-bottom: 30px; text-align: center;\">\r\n");
      out.write("                        <h3 style=\"margin-bottom: 10px;\">🎉 Đăng ký thành công!</h3>\r\n");
      out.write("                        <p>Cảm ơn bạn đã đăng ký Newsletter ABC News. Chúng tôi sẽ gửi những tin tức mới nhất và hấp dẫn nhất đến email của bạn.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Newsletter Benefits -->\r\n");
      out.write("                    <div style=\"display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 25px; margin-bottom: 40px;\">\r\n");
      out.write("                        <div style=\"background: white; padding: 30px; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); text-align: center; border-top: 4px solid #c41e3a;\">\r\n");
      out.write("                            <div style=\"font-size: 3rem; margin-bottom: 15px;\">⚡</div>\r\n");
      out.write("                            <h3 style=\"color: #c41e3a; margin-bottom: 15px;\">Tin nhanh nhất</h3>\r\n");
      out.write("                            <p style=\"color: #666; line-height: 1.6;\">Nhận tin tức nóng hổi ngay khi có sự kiện quan trọng xảy ra, không bỏ lỡ bất kỳ thông tin nào.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div style=\"background: white; padding: 30px; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); text-align: center; border-top: 4px solid #c41e3a;\">\r\n");
      out.write("                            <div style=\"font-size: 3rem; margin-bottom: 15px;\">🎯</div>\r\n");
      out.write("                            <h3 style=\"color: #c41e3a; margin-bottom: 15px;\">Nội dung chọn lọc</h3>\r\n");
      out.write("                            <p style=\"color: #666; line-height: 1.6;\">Chỉ những tin tức quan trọng và có giá trị nhất được tuyển chọn kỹ lưỡng bởi đội ngũ biên tập viên.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div style=\"background: white; padding: 30px; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); text-align: center; border-top: 4px solid #c41e3a;\">\r\n");
      out.write("                            <div style=\"font-size: 3rem; margin-bottom: 15px;\">📱</div>\r\n");
      out.write("                            <h3 style=\"color: #c41e3a; margin-bottom: 15px;\">Đa nền tảng</h3>\r\n");
      out.write("                            <p style=\"color: #666; line-height: 1.6;\">Tương thích hoàn hảo trên mọi thiết bị: máy tính, điện thoại, tablet với giao diện tối ưu.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div style=\"background: white; padding: 30px; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); text-align: center; border-top: 4px solid #c41e3a;\">\r\n");
      out.write("                            <div style=\"font-size: 3rem; margin-bottom: 15px;\">🔒</div>\r\n");
      out.write("                            <h3 style=\"color: #c41e3a; margin-bottom: 15px;\">Bảo mật tuyệt đối</h3>\r\n");
      out.write("                            <p style=\"color: #666; line-height: 1.6;\">Thông tin cá nhân của bạn được bảo vệ nghiêm ngặt, không chia sẻ với bên thứ ba.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div style=\"background: white; padding: 30px; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); text-align: center; border-top: 4px solid #c41e3a;\">\r\n");
      out.write("                            <div style=\"font-size: 3rem; margin-bottom: 15px;\">🎁</div>\r\n");
      out.write("                            <h3 style=\"color: #c41e3a; margin-bottom: 15px;\">Hoàn toàn miễn phí</h3>\r\n");
      out.write("                            <p style=\"color: #666; line-height: 1.6;\">Dịch vụ Newsletter hoàn toàn miễn phí, không có phí ẩn hay chi phí phát sinh.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div style=\"background: white; padding: 30px; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); text-align: center; border-top: 4px solid #c41e3a;\">\r\n");
      out.write("                            <div style=\"font-size: 3rem; margin-bottom: 15px;\">❌</div>\r\n");
      out.write("                            <h3 style=\"color: #c41e3a; margin-bottom: 15px;\">Hủy bất cứ lúc nào</h3>\r\n");
      out.write("                            <p style=\"color: #666; line-height: 1.6;\">Có thể hủy đăng ký dễ dàng chỉ với một cú click, không cần giải thích lý do.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Newsletter Subscription Form -->\r\n");
      out.write("                    <div style=\"background: white; padding: 40px; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); margin-bottom: 40px;\">\r\n");
      out.write("                        <h2 style=\"text-align: center; color: #c41e3a; margin-bottom: 30px; font-size: 2rem;\">📝 Đăng ký Newsletter</h2>\r\n");
      out.write("                        \r\n");
      out.write("                        <form id=\"newsletterForm\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/docgia/newsletter.jsp\" method=\"post\" style=\"max-width: 600px; margin: 0 auto;\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"email\" style=\"font-size: 1.1rem; color: #333;\">📧 Địa chỉ email của bạn:</label>\r\n");
      out.write("                                <input type=\"email\" id=\"email\" name=\"email\" placeholder=\"Ví dụ: your.email@gmail.com\" required \r\n");
      out.write("                                       style=\"font-size: 1.1rem; padding: 15px 20px; border: 2px solid #e0e0e0; border-radius: 8px;\">\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label style=\"font-size: 1.1rem; color: #333; margin-bottom: 15px; display: block;\">📂 Chọn chuyên mục quan tâm:</label>\r\n");
      out.write("                                <div style=\"display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px;\">\r\n");
      out.write("                                    <label style=\"display: flex; align-items: center; gap: 10px; padding: 12px; border: 1px solid #e0e0e0; border-radius: 6px; cursor: pointer; transition: all 0.3s;\" onmouseover=\"this.style.background='#f8f9fa'\" onmouseout=\"this.style.background='white'\">\r\n");
      out.write("                                        <input type=\"checkbox\" name=\"categories\" value=\"news\" checked style=\"transform: scale(1.2);\">\r\n");
      out.write("                                        <span>📰 Tin tức tổng hợp</span>\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <label style=\"display: flex; align-items: center; gap: 10px; padding: 12px; border: 1px solid #e0e0e0; border-radius: 6px; cursor: pointer; transition: all 0.3s;\" onmouseover=\"this.style.background='#f8f9fa'\" onmouseout=\"this.style.background='white'\">\r\n");
      out.write("                                        <input type=\"checkbox\" name=\"categories\" value=\"sports\" style=\"transform: scale(1.2);\">\r\n");
      out.write("                                        <span>⚽ Thể thao</span>\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <label style=\"display: flex; align-items: center; gap: 10px; padding: 12px; border: 1px solid #e0e0e0; border-radius: 6px; cursor: pointer; transition: all 0.3s;\" onmouseover=\"this.style.background='#f8f9fa'\" onmouseout=\"this.style.background='white'\">\r\n");
      out.write("                                        <input type=\"checkbox\" name=\"categories\" value=\"business\" style=\"transform: scale(1.2);\">\r\n");
      out.write("                                        <span>💼 Kinh doanh</span>\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <label style=\"display: flex; align-items: center; gap: 10px; padding: 12px; border: 1px solid #e0e0e0; border-radius: 6px; cursor: pointer; transition: all 0.3s;\" onmouseover=\"this.style.background='#f8f9fa'\" onmouseout=\"this.style.background='white'\">\r\n");
      out.write("                                        <input type=\"checkbox\" name=\"categories\" value=\"tech\" style=\"transform: scale(1.2);\">\r\n");
      out.write("                                        <span>💻 Công nghệ</span>\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <label style=\"display: flex; align-items: center; gap: 10px; padding: 12px; border: 1px solid #e0e0e0; border-radius: 6px; cursor: pointer; transition: all 0.3s;\" onmouseover=\"this.style.background='#f8f9fa'\" onmouseout=\"this.style.background='white'\">\r\n");
      out.write("                                        <input type=\"checkbox\" name=\"categories\" value=\"entertainment\" style=\"transform: scale(1.2);\">\r\n");
      out.write("                                        <span>🎭 Giải trí</span>\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <label style=\"display: flex; align-items: center; gap: 10px; padding: 12px; border: 1px solid #e0e0e0; border-radius: 6px; cursor: pointer; transition: all 0.3s;\" onmouseover=\"this.style.background='#f8f9fa'\" onmouseout=\"this.style.background='white'\">\r\n");
      out.write("                                        <input type=\"checkbox\" name=\"categories\" value=\"health\" style=\"transform: scale(1.2);\">\r\n");
      out.write("                                        <span>🏥 Sức khỏe</span>\r\n");
      out.write("                                    </label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label style=\"font-size: 1.1rem; color: #333;\">⏰ Tần suất nhận email:</label>\r\n");
      out.write("                                <select name=\"frequency\" style=\"font-size: 1.1rem; padding: 15px 20px; border: 2px solid #e0e0e0; border-radius: 8px;\">\r\n");
      out.write("                                    <option value=\"daily\">Hàng ngày (7:00 AM)</option>\r\n");
      out.write("                                    <option value=\"weekly\" selected>Hàng tuần (Chủ nhật 8:00 AM)</option>\r\n");
      out.write("                                    <option value=\"breaking\">Chỉ tin nóng</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div style=\"display: flex; align-items: center; gap: 10px; margin-bottom: 25px;\">\r\n");
      out.write("                                <input type=\"checkbox\" id=\"agree\" name=\"agree\" required style=\"transform: scale(1.3);\">\r\n");
      out.write("                                <label for=\"agree\" style=\"font-size: 14px; color: #666;\">\r\n");
      out.write("                                    Tôi đồng ý với <a href=\"#\" style=\"color: #c41e3a;\">Điều khoản sử dụng</a> và <a href=\"#\" style=\"color: #c41e3a;\">Chính sách bảo mật</a> của ABC News\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div style=\"text-align: center;\">\r\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-primary\" style=\"font-size: 1.2rem; padding: 15px 40px; background: linear-gradient(135deg, #c41e3a, #a01729);\">\r\n");
      out.write("                                    📧 Đăng ký Newsletter ngay\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Newsletter Management -->\r\n");
      out.write("                    <div style=\"background: #f8f9fa; padding: 40px; border-radius: 12px; margin-bottom: 40px;\">\r\n");
      out.write("                        <h2 style=\"text-align: center; color: #c41e3a; margin-bottom: 30px; font-size: 2rem;\">⚙️ Quản lý đăng ký</h2>\r\n");
      out.write("                        \r\n");
      out.write("                        <div style=\"display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 30px;\">\r\n");
      out.write("                            <div style=\"text-align: center;\">\r\n");
      out.write("                                <div style=\"font-size: 3rem; margin-bottom: 15px;\">✏️</div>\r\n");
      out.write("                                <h3 style=\"color: #333; margin-bottom: 15px;\">Cập nhật thông tin</h3>\r\n");
      out.write("                                <p style=\"color: #666; margin-bottom: 20px; line-height: 1.6;\">\r\n");
      out.write("                                    Thay đổi email, chuyên mục quan tâm hoặc tần suất nhận tin\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <button class=\"btn btn-warning\" onclick=\"showUpdateForm()\">Cập nhật</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div style=\"text-align: center;\">\r\n");
      out.write("                                <div style=\"font-size: 3rem; margin-bottom: 15px;\">⏸️</div>\r\n");
      out.write("                                <h3 style=\"color: #333; margin-bottom: 15px;\">Tạm dừng</h3>\r\n");
      out.write("                                <p style=\"color: #666; margin-bottom: 20px; line-height: 1.6;\">\r\n");
      out.write("                                    Tạm dừng nhận email trong một khoảng thời gian nhất định\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <button class=\"btn btn-warning\" onclick=\"pauseNewsletter()\">Tạm dừng</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div style=\"text-align: center;\">\r\n");
      out.write("                                <div style=\"font-size: 3rem; margin-bottom: 15px;\">❌</div>\r\n");
      out.write("                                <h3 style=\"color: #333; margin-bottom: 15px;\">Hủy đăng ký</h3>\r\n");
      out.write("                                <p style=\"color: #666; margin-bottom: 20px; line-height: 1.6;\">\r\n");
      out.write("                                    Hủy hoàn toàn việc nhận Newsletter từ ABC News\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <button class=\"btn btn-danger\" onclick=\"unsubscribeNewsletter()\">Hủy đăng ký</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Newsletter Statistics -->\r\n");
      out.write("                    <div style=\"background: white; padding: 40px; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); margin-bottom: 40px;\">\r\n");
      out.write("                        <h2 style=\"text-align: center; color: #c41e3a; margin-bottom: 30px; font-size: 2rem;\">📊 Thống kê Newsletter</h2>\r\n");
      out.write("                        \r\n");
      out.write("                        <div style=\"display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 25px;\">\r\n");
      out.write("                            <div style=\"text-align: center; padding: 25px; background: #f8f9fa; border-radius: 8px;\">\r\n");
      out.write("                                <div style=\"font-size: 2.5rem; color: #c41e3a; font-weight: bold; margin-bottom: 10px;\">12,547</div>\r\n");
      out.write("                                <div style=\"color: #666; font-size: 14px;\">Người đăng ký</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div style=\"text-align: center; padding: 25px; background: #f8f9fa; border-radius: 8px;\">\r\n");
      out.write("                                <div style=\"font-size: 2.5rem; color: #28a745; font-weight: bold; margin-bottom: 10px;\">98.5%</div>\r\n");
      out.write("                                <div style=\"color: #666; font-size: 14px;\">Tỷ lệ gửi thành công</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div style=\"text-align: center; padding: 25px; background: #f8f9fa; border-radius: 8px;\">\r\n");
      out.write("                                <div style=\"font-size: 2.5rem; color: #17a2b8; font-weight: bold; margin-bottom: 10px;\">76.3%</div>\r\n");
      out.write("                                <div style=\"color: #666; font-size: 14px;\">Tỷ lệ mở email</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div style=\"text-align: center; padding: 25px; background: #f8f9fa; border-radius: 8px;\">\r\n");
      out.write("                                <div style=\"font-size: 2.5rem; color: #ffc107; font-weight: bold; margin-bottom: 10px;\">45.2%</div>\r\n");
      out.write("                                <div style=\"color: #666; font-size: 14px;\">Tỷ lệ click</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Sample Newsletter -->\r\n");
      out.write("                    <div style=\"background: white; padding: 40px; border-radius: 12px; box-shadow: 0 4px 15px rgba(0,0,0,0.1);\">\r\n");
      out.write("                        <h2 style=\"text-align: center; color: #c41e3a; margin-bottom: 30px; font-size: 2rem;\">📮 Mẫu Newsletter</h2>\r\n");
      out.write("                        \r\n");
      out.write("                        <div style=\"max-width: 600px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 8px; overflow: hidden;\">\r\n");
      out.write("                            <!-- Email Header -->\r\n");
      out.write("                            <div style=\"background: #c41e3a; color: white; padding: 20px; text-align: center;\">\r\n");
      out.write("                                <h3 style=\"margin: 0; font-size: 1.5rem;\">ABC NEWS</h3>\r\n");
      out.write("                                <p style=\"margin: 5px 0 0 0; opacity: 0.9;\">Newsletter hàng tuần</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Email Content -->\r\n");
      out.write("                            <div style=\"padding: 30px;\">\r\n");
      out.write("                                <h4 style=\"color: #c41e3a; margin-bottom: 15px;\">🔥 Tin nóng trong tuần</h4>\r\n");
      out.write("                                <div style=\"border-left: 3px solid #c41e3a; padding-left: 15px; margin-bottom: 20px;\">\r\n");
      out.write("                                    <h5 style=\"margin: 0 0 5px 0; color: #333;\">Đội tuyển Việt Nam giành chiến thắng lịch sử</h5>\r\n");
      out.write("                                    <p style=\"margin: 0; color: #666; font-size: 14px;\">Chiến thắng 4-0 trước Nhật Bản mở ra cơ hội dự World Cup...</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <h4 style=\"color: #c41e3a; margin-bottom: 15px;\">💼 Kinh doanh</h4>\r\n");
      out.write("                                <div style=\"border-left: 3px solid #c41e3a; padding-left: 15px; margin-bottom: 20px;\">\r\n");
      out.write("                                    <h5 style=\"margin: 0 0 5px 0; color: #333;\">Chứng khoán Việt Nam tăng mạnh</h5>\r\n");
      out.write("                                    <p style=\"margin: 0; color: #666; font-size: 14px;\">VN-Index vượt mốc 1.300 điểm sau tin tích cực...</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <h4 style=\"color: #c41e3a; margin-bottom: 15px;\">💻 Công nghệ</h4>\r\n");
      out.write("                                <div style=\"border-left: 3px solid #c41e3a; padding-left: 15px; margin-bottom: 20px;\">\r\n");
      out.write("                                    <h5 style=\"margin: 0 0 5px 0; color: #333;\">ChatGPT-5 sẽ ra mắt cuối năm</h5>\r\n");
      out.write("                                    <p style=\"margin: 0; color: #666; font-size: 14px;\">OpenAI công bố kế hoạch phát hành phiên bản mới...</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Email Footer -->\r\n");
      out.write("                            <div style=\"background: #f8f9fa; padding: 20px; text-align: center; font-size: 12px; color: #666;\">\r\n");
      out.write("                                <p style=\"margin: 0 0 10px 0;\">© 2025 ABC News. Bản quyền thuộc về ABC News.</p>\r\n");
      out.write("                                <p style=\"margin: 0;\">\r\n");
      out.write("                                    <a href=\"#\" style=\"color: #c41e3a;\">Cập nhật thông tin</a> | \r\n");
      out.write("                                    <a href=\"#\" style=\"color: #c41e3a;\">Hủy đăng ký</a>\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </main>\r\n");
      out.write("\r\n");
      out.write("                <!-- Sidebar -->\r\n");
      out.write("                <aside class=\"sidebar\">\r\n");
      out.write("                    <!-- Newsletter Stats Widget -->\r\n");
      out.write("                    <div class=\"widget\">\r\n");
      out.write("                        <div class=\"widget-header\">\r\n");
      out.write("                            📈 Thống kê Newsletter\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"widget-content\">\r\n");
      out.write("                            <div style=\"text-align: center; margin-bottom: 20px;\">\r\n");
      out.write("                                <div style=\"font-size: 2rem; color: #c41e3a; font-weight: bold;\">12,547</div>\r\n");
      out.write("                                <div style=\"color: #666; font-size: 13px;\">Người đăng ký</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            \r\n");
      out.write("                            <div style=\"margin-bottom: 15px;\">\r\n");
      out.write("                                <div style=\"display: flex; justify-content: space-between; margin-bottom: 5px;\">\r\n");
      out.write("                                    <span style=\"font-size: 13px;\">Tin tức tổng hợp</span>\r\n");
      out.write("                                    <span style=\"font-size: 13px; color: #c41e3a;\">8,234</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div style=\"background: #f0f0f0; height: 6px; border-radius: 3px;\">\r\n");
      out.write("                                    <div style=\"background: #c41e3a; height: 6px; width: 65%; border-radius: 3px;\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div style=\"margin-bottom: 15px;\">\r\n");
      out.write("                                <div style=\"display: flex; justify-content: space-between; margin-bottom: 5px;\">\r\n");
      out.write("                                    <span style=\"font-size: 13px;\">Thể thao</span>\r\n");
      out.write("                                    <span style=\"font-size: 13px; color: #c41e3a;\">5,123</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div style=\"background: #f0f0f0; height: 6px; border-radius: 3px;\">\r\n");
      out.write("                                    <div style=\"background: #c41e3a; height: 6px; width: 41%; border-radius: 3px;\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div style=\"margin-bottom: 15px;\">\r\n");
      out.write("                                <div style=\"display: flex; justify-content: space-between; margin-bottom: 5px;\">\r\n");
      out.write("                                    <span style=\"font-size: 13px;\">Công nghệ</span>\r\n");
      out.write("                                    <span style=\"font-size: 13px; color: #c41e3a;\">3,456</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div style=\"background: #f0f0f0; height: 6px; border-radius: 3px;\">\r\n");
      out.write("                                    <div style=\"background: #c41e3a; height: 6px; width: 28%; border-radius: 3px;\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Recent Newsletters Widget -->\r\n");
      out.write("                    <div class=\"widget\">\r\n");
      out.write("                        <div class=\"widget-header\">\r\n");
      out.write("                            📮 Newsletter gần đây\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"widget-content\">\r\n");
      out.write("                            <ul class=\"widget-list\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div style=\"width: 60px; height: 45px; background: #c41e3a; border-radius: 4px; display: flex; align-items: center; justify-content: center; color: white; font-size: 12px; flex-shrink: 0;\">\r\n");
      out.write("                                        29/09\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"widget-item-content\">\r\n");
      out.write("                                        <a href=\"#\" class=\"widget-item-title\">\r\n");
      out.write("                                            Newsletter tuần 39: Thể thao Việt Nam tỏa sáng\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <div class=\"widget-item-meta\">Chủ nhật • 12,547 người nhận</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div style=\"width: 60px; height: 45px; background: #c41e3a; border-radius: 4px; display: flex; align-items: center; justify-content: center; color: white; font-size: 12px; flex-shrink: 0;\">\r\n");
      out.write("                                        22/09\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"widget-item-content\">\r\n");
      out.write("                                        <a href=\"#\" class=\"widget-item-title\">\r\n");
      out.write("                                            Newsletter tuần 38: Công nghệ AI bùng nổ\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <div class=\"widget-item-meta\">Chủ nhật • 12,234 người nhận</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <div style=\"width: 60px; height: 45px; background: #c41e3a; border-radius: 4px; display: flex; align-items: center; justify-content: center; color: white; font-size: 12px; flex-shrink: 0;\">\r\n");
      out.write("                                        15/09\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"widget-item-content\">\r\n");
      out.write("                                        <a href=\"#\" class=\"widget-item-title\">\r\n");
      out.write("                                            Newsletter tuần 37: Kinh tế Việt Nam phục hồi\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <div class=\"widget-item-meta\">Chủ nhật • 11,987 người nhận</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Contact Widget -->\r\n");
      out.write("                    <div class=\"widget\">\r\n");
      out.write("                        <div class=\"widget-header\">\r\n");
      out.write("                            📞 Hỗ trợ Newsletter\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"widget-content\">\r\n");
      out.write("                            <p style=\"margin-bottom: 15px; font-size: 14px; color: #666;\">\r\n");
      out.write("                                Cần hỗ trợ về Newsletter? Liên hệ với chúng tôi:\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <ul style=\"list-style: none; font-size: 13px; line-height: 1.8;\">\r\n");
      out.write("                                <li>📧 newsletter@abcnews.vn</li>\r\n");
      out.write("                                <li>📞 1900-1234 (ext. 3)</li>\r\n");
      out.write("                                <li>💬 Chat trực tuyến</li>\r\n");
      out.write("                                <li>🕒 Hỗ trợ 24/7</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </aside>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <footer class=\"footer\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"footer-content\">\r\n");
      out.write("                <div class=\"footer-section\">\r\n");
      out.write("                    <h3>ABC News</h3>\r\n");
      out.write("                    <p style=\"margin-bottom: 15px; font-size: 14px; line-height: 1.6;\">\r\n");
      out.write("                        Trang tin tức hàng đầu Việt Nam, cập nhật tin nhanh và chính xác 24/7\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <div style=\"display: flex; gap: 10px;\">\r\n");
      out.write("                        <a href=\"#\" style=\"font-size: 20px;\">📘</a>\r\n");
      out.write("                        <a href=\"#\" style=\"font-size: 20px;\">🐦</a>\r\n");
      out.write("                        <a href=\"#\" style=\"font-size: 20px;\">📺</a>\r\n");
      out.write("                        <a href=\"#\" style=\"font-size: 20px;\">📷</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"footer-section\">\r\n");
      out.write("                    <h3>Newsletter</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"#\">Đăng ký mới</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Cập nhật thông tin</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Hủy đăng ký</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Lịch sử Newsletter</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Chính sách bảo mật</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"footer-section\">\r\n");
      out.write("                    <h3>Dịch vụ</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/docgia/newsletter.jsp\">Newsletter</a></li>\r\n");
      out.write("                        <li><a href=\"#\">RSS</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Mobile App</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Quảng cáo</a></li>\r\n");
      out.write("                        <li><a href=\"#\">Liên hệ</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"footer-section\">\r\n");
      out.write("                    <h3>Liên hệ</h3>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>📍 123 Đường ABC, Quận 1, TP.HCM</li>\r\n");
      out.write("                        <li>📞 Hotline: 1900-1234</li>\r\n");
      out.write("                        <li>📧 Email: newsletter@abcnews.vn</li>\r\n");
      out.write("                        <li>🕒 Làm việc: 24/7</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"footer-bottom\">\r\n");
      out.write("                <p>&copy; 2025 ABC News. Bản quyền thuộc về ABC News. | \r\n");
      out.write("                   <a href=\"#\" style=\"color: #c41e3a;\">Chính sách bảo mật</a> | \r\n");
      out.write("                   <a href=\"#\" style=\"color: #c41e3a;\">Điều khoản sử dụng</a>\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        // Display current date\r\n");
      out.write("        function updateCurrentDate() {\r\n");
      out.write("            const now = new Date();\r\n");
      out.write("            const options = { \r\n");
      out.write("                weekday: 'long', \r\n");
      out.write("                year: 'numeric', \r\n");
      out.write("                month: 'long', \r\n");
      out.write("                day: 'numeric',\r\n");
      out.write("                timeZone: 'Asia/Ho_Chi_Minh'\r\n");
      out.write("            };\r\n");
      out.write("            document.getElementById('currentDate').textContent = \r\n");
      out.write("                now.toLocaleDateString('vi-VN', options);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Newsletter form submission\r\n");
      out.write("        document.getElementById('newsletterForm').addEventListener('submit', function(e) {\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            \r\n");
      out.write("            // Show success message\r\n");
      out.write("            document.getElementById('successMessage').style.display = 'block';\r\n");
      out.write("            \r\n");
      out.write("            // Scroll to success message\r\n");
      out.write("            document.getElementById('successMessage').scrollIntoView({ \r\n");
      out.write("                behavior: 'smooth', \r\n");
      out.write("                block: 'center' \r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            // Reset form\r\n");
      out.write("            this.reset();\r\n");
      out.write("            \r\n");
      out.write("            // Re-check the default category\r\n");
      out.write("            document.querySelector('input[name=\"categories\"][value=\"news\"]').checked = true;\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Management functions\r\n");
      out.write("        function showUpdateForm() {\r\n");
      out.write("            alert('Tính năng cập nhật thông tin sẽ được phát triển trong giai đoạn tiếp theo.');\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function pauseNewsletter() {\r\n");
      out.write("            if (confirm('Bạn có chắc chắn muốn tạm dừng nhận Newsletter?')) {\r\n");
      out.write("                alert('Đã tạm dừng Newsletter. Bạn có thể kích hoạt lại bất cứ lúc nào.');\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function unsubscribeNewsletter() {\r\n");
      out.write("            if (confirm('Bạn có chắc chắn muốn hủy đăng ký Newsletter? Bạn sẽ không nhận được tin tức mới nhất từ ABC News.')) {\r\n");
      out.write("                alert('Đã hủy đăng ký Newsletter thành công. Cảm ơn bạn đã đồng hành cùng ABC News!');\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        // Initialize\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("            updateCurrentDate();\r\n");
      out.write("            setInterval(updateCurrentDate, 60000);\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
