/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.11
 * Generated at: 2025-10-21 16:48:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1760802865264L));
    _jspx_dependants.put("jar:file:/H:/web_abcnew_asignment/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/abc_new/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664428278000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        <!DOCTYPE html>\r\n");
      out.write("        <html lang=\"vi\">\r\n");
      out.write("\r\n");
      out.write("        <head>\r\n");
      out.write("            <meta charset=\"UTF-8\">\r\n");
      out.write("            <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("            <title>Đăng nhập - ABC News</title>\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\r\n");
      out.write("            <link rel=\"icon\" type=\"image/x-icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/favicon.ico\">\r\n");
      out.write("            <style>\r\n");
      out.write("                .login-wrapper {\r\n");
      out.write("                    min-height: 100vh;\r\n");
      out.write("                    background: linear-gradient(135deg, #c41e3a 0%, #a01729 100%);\r\n");
      out.write("                    display: flex;\r\n");
      out.write("                    align-items: center;\r\n");
      out.write("                    justify-content: center;\r\n");
      out.write("                    padding: 20px;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .login-container {\r\n");
      out.write("                    background: white;\r\n");
      out.write("                    border-radius: 15px;\r\n");
      out.write("                    box-shadow: 0 15px 35px rgba(0, 0, 0, 0.1);\r\n");
      out.write("                    overflow: hidden;\r\n");
      out.write("                    width: 100%;\r\n");
      out.write("                    max-width: 900px;\r\n");
      out.write("                    display: grid;\r\n");
      out.write("                    grid-template-columns: 1fr 1fr;\r\n");
      out.write("                    min-height: 600px;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .login-left {\r\n");
      out.write("                    background: linear-gradient(135deg, #c41e3a, #a01729);\r\n");
      out.write("                    color: white;\r\n");
      out.write("                    padding: 60px 40px;\r\n");
      out.write("                    display: flex;\r\n");
      out.write("                    flex-direction: column;\r\n");
      out.write("                    justify-content: center;\r\n");
      out.write("                    text-align: center;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .login-right {\r\n");
      out.write("                    padding: 60px 40px;\r\n");
      out.write("                    display: flex;\r\n");
      out.write("                    flex-direction: column;\r\n");
      out.write("                    justify-content: center;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .login-logo {\r\n");
      out.write("                    font-size: 3rem;\r\n");
      out.write("                    font-weight: bold;\r\n");
      out.write("                    margin-bottom: 20px;\r\n");
      out.write("                    text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .login-tagline {\r\n");
      out.write("                    font-size: 1.2rem;\r\n");
      out.write("                    opacity: 0.9;\r\n");
      out.write("                    margin-bottom: 30px;\r\n");
      out.write("                    line-height: 1.6;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .login-features {\r\n");
      out.write("                    list-style: none;\r\n");
      out.write("                    text-align: left;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .login-features li {\r\n");
      out.write("                    margin-bottom: 15px;\r\n");
      out.write("                    display: flex;\r\n");
      out.write("                    align-items: center;\r\n");
      out.write("                    gap: 10px;\r\n");
      out.write("                    font-size: 1rem;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .login-form h2 {\r\n");
      out.write("                    color: #c41e3a;\r\n");
      out.write("                    margin-bottom: 30px;\r\n");
      out.write("                    font-size: 2rem;\r\n");
      out.write("                    text-align: center;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .role-tabs {\r\n");
      out.write("                    display: flex;\r\n");
      out.write("                    margin-bottom: 30px;\r\n");
      out.write("                    background: #f8f9fa;\r\n");
      out.write("                    border-radius: 8px;\r\n");
      out.write("                    padding: 4px;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .role-tab {\r\n");
      out.write("                    flex: 1;\r\n");
      out.write("                    padding: 12px 20px;\r\n");
      out.write("                    text-align: center;\r\n");
      out.write("                    border-radius: 6px;\r\n");
      out.write("                    cursor: pointer;\r\n");
      out.write("                    transition: all 0.3s;\r\n");
      out.write("                    font-weight: 500;\r\n");
      out.write("                    color: #666;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .role-tab.active {\r\n");
      out.write("                    background: #c41e3a;\r\n");
      out.write("                    color: white;\r\n");
      out.write("                    box-shadow: 0 2px 8px rgba(196, 30, 58, 0.3);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .form-group {\r\n");
      out.write("                    margin-bottom: 25px;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .form-group label {\r\n");
      out.write("                    display: block;\r\n");
      out.write("                    margin-bottom: 8px;\r\n");
      out.write("                    font-weight: 500;\r\n");
      out.write("                    color: #333;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .form-group input {\r\n");
      out.write("                    width: 100%;\r\n");
      out.write("                    padding: 15px 20px;\r\n");
      out.write("                    border: 2px solid #e0e0e0;\r\n");
      out.write("                    border-radius: 8px;\r\n");
      out.write("                    font-size: 16px;\r\n");
      out.write("                    transition: border-color 0.3s;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .form-group input:focus {\r\n");
      out.write("                    outline: none;\r\n");
      out.write("                    border-color: #c41e3a;\r\n");
      out.write("                    box-shadow: 0 0 0 3px rgba(196, 30, 58, 0.1);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .login-btn {\r\n");
      out.write("                    width: 100%;\r\n");
      out.write("                    padding: 15px;\r\n");
      out.write("                    background: linear-gradient(135deg, #c41e3a, #a01729);\r\n");
      out.write("                    color: white;\r\n");
      out.write("                    border: none;\r\n");
      out.write("                    border-radius: 8px;\r\n");
      out.write("                    font-size: 16px;\r\n");
      out.write("                    font-weight: bold;\r\n");
      out.write("                    cursor: pointer;\r\n");
      out.write("                    transition: transform 0.3s;\r\n");
      out.write("                    margin-bottom: 20px;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .login-btn:hover {\r\n");
      out.write("                    transform: translateY(-2px);\r\n");
      out.write("                    box-shadow: 0 5px 15px rgba(196, 30, 58, 0.3);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .error-message {\r\n");
      out.write("                    background: #f8d7da;\r\n");
      out.write("                    color: #721c24;\r\n");
      out.write("                    padding: 12px;\r\n");
      out.write("                    border-radius: 6px;\r\n");
      out.write("                    margin-bottom: 20px;\r\n");
      out.write("                    border: 1px solid #f5c6cb;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .demo-accounts {\r\n");
      out.write("                    background: #f8f9fa;\r\n");
      out.write("                    padding: 20px;\r\n");
      out.write("                    border-radius: 8px;\r\n");
      out.write("                    margin-top: 20px;\r\n");
      out.write("                    font-size: 14px;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .demo-accounts h4 {\r\n");
      out.write("                    color: #c41e3a;\r\n");
      out.write("                    margin-bottom: 15px;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .demo-account {\r\n");
      out.write("                    display: flex;\r\n");
      out.write("                    justify-content: space-between;\r\n");
      out.write("                    align-items: center;\r\n");
      out.write("                    padding: 8px 0;\r\n");
      out.write("                    border-bottom: 1px solid #e0e0e0;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .demo-account:last-child {\r\n");
      out.write("                    border-bottom: none;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .demo-btn {\r\n");
      out.write("                    background: #28a745;\r\n");
      out.write("                    color: white;\r\n");
      out.write("                    border: none;\r\n");
      out.write("                    padding: 5px 12px;\r\n");
      out.write("                    border-radius: 4px;\r\n");
      out.write("                    font-size: 12px;\r\n");
      out.write("                    cursor: pointer;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .back-home {\r\n");
      out.write("                    text-align: center;\r\n");
      out.write("                    margin-top: 30px;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                .back-home a {\r\n");
      out.write("                    color: #c41e3a;\r\n");
      out.write("                    text-decoration: none;\r\n");
      out.write("                    font-weight: 500;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                @media (max-width: 768px) {\r\n");
      out.write("                    .login-container {\r\n");
      out.write("                        grid-template-columns: 1fr;\r\n");
      out.write("                        max-width: 400px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .login-left {\r\n");
      out.write("                        padding: 40px 30px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .login-right {\r\n");
      out.write("                        padding: 40px 30px;\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    .login-logo {\r\n");
      out.write("                        font-size: 2.5rem;\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            </style>\r\n");
      out.write("        </head>\r\n");
      out.write("\r\n");
      out.write("        <body>\r\n");
      out.write("            <div class=\"login-wrapper\">\r\n");
      out.write("                <div class=\"login-container\">\r\n");
      out.write("                    <!-- Left Side - Branding -->\r\n");
      out.write("                    <div class=\"login-left\">\r\n");
      out.write("                        <div class=\"login-logo\">ABC NEWS</div>\r\n");
      out.write("                        <div class=\"login-tagline\">\r\n");
      out.write("                            Hệ thống quản lý tin tức hàng đầu Việt Nam\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <ul class=\"login-features\">\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <span>✅</span>\r\n");
      out.write("                                <span>Quản lý tin tức chuyên nghiệp</span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <span>✅</span>\r\n");
      out.write("                                <span>Giao diện thân thiện, dễ sử dụng</span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <span>✅</span>\r\n");
      out.write("                                <span>Bảo mật thông tin tuyệt đối</span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <span>✅</span>\r\n");
      out.write("                                <span>Hỗ trợ đa nền tảng</span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <span>✅</span>\r\n");
      out.write("                                <span>Cập nhật realtime 24/7</span>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Right Side - Login Form -->\r\n");
      out.write("                    <div class=\"login-right\">\r\n");
      out.write("                        <form class=\"login-form\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\" method=\"post\">\r\n");
      out.write("                            <h2>🔐 Đăng nhập</h2>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Error Message -->\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <!-- Success Message -->\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <!-- Display error message if exists -->\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"username\">👤 Tên đăng nhập:</label>\r\n");
      out.write("                                <input type=\"text\" id=\"username\" name=\"username\" placeholder=\"Nhập tên đăng nhập\"\r\n");
      out.write("                                    value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty rememberedUsername ? rememberedUsername : username}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"password\">🔒 Mật khẩu:</label>\r\n");
      out.write("                                <input type=\"password\" id=\"password\" name=\"password\" placeholder=\"Nhập mật khẩu\"\r\n");
      out.write("                                    value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty rememberedPassword ? rememberedPassword : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div\r\n");
      out.write("                                style=\"display: flex; align-items: center; justify-content: space-between; margin-bottom: 25px;\">\r\n");
      out.write("                                <label style=\"display: flex; align-items: center; gap: 8px; font-size: 14px;\">\r\n");
      out.write("                                    <input type=\"checkbox\" name=\"rememberMe\" value=\"1\" style=\"width: auto;\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${rememberMe\r\n                                        ? 'checked' : '' }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("                                    <span>🍪 Ghi nhớ đăng nhập (7 ngày)</span>\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <button type=\"submit\" class=\"login-btn\">\r\n");
      out.write("                                🚀 Đăng nhập ngay\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Demo Accounts -->\r\n");
      out.write("                        <div class=\"demo-accounts\">\r\n");
      out.write("                            <h4>🎯 Tài khoản demo để test:</h4>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"demo-account\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <strong>Admin:</strong> admin / 123456\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <button type=\"button\" class=\"demo-btn\" onclick=\"fillDemo('admin', '123456')\">\r\n");
      out.write("                                    Dùng thử\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"demo-account\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <strong>Phóng viên:</strong> pv001 / 123456\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <button type=\"button\" class=\"demo-btn\" onclick=\"fillDemo('pv001', '123456')\">\r\n");
      out.write("                                    Dùng thử\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"demo-account\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <strong>Phóng viên:</strong> pv002 / 123456\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <button type=\"button\" class=\"demo-btn\" onclick=\"fillDemo('pv002', '123456')\">\r\n");
      out.write("                                    Dùng thử\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"back-home\">\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/home\">← Quay về trang chủ ABC\r\n");
      out.write("                                News</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <script>\r\n");
      out.write("                // Fill demo account\r\n");
      out.write("                function fillDemo(username, password) {\r\n");
      out.write("                    document.getElementById('username').value = username;\r\n");
      out.write("                    document.getElementById('password').value = password;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // Focus first input\r\n");
      out.write("                document.addEventListener('DOMContentLoaded', function () {\r\n");
      out.write("                    document.getElementById('username').focus();\r\n");
      out.write("                });\r\n");
      out.write("            </script>\r\n");
      out.write("        </body>\r\n");
      out.write("\r\n");
      out.write("        </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /login.jsp(271,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty error}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                                <div\r\n");
        out.write("                                    style=\"background: #f8d7da; color: #721c24; padding: 12px; border-radius: 6px; margin-bottom: 20px; border: 1px solid #f5c6cb;\">\r\n");
        out.write("                                    <strong>❌ Lỗi:</strong> ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\r\n");
        out.write("                                </div>\r\n");
        out.write("                            ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /login.jsp(279,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty success}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                                <div\r\n");
        out.write("                                    style=\"background: #d4edda; color: #155724; padding: 12px; border-radius: 6px; margin-bottom: 20px; border: 1px solid #c3e6cb;\">\r\n");
        out.write("                                    <strong>✅ Thành công:</strong> ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${success}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\r\n");
        out.write("                                </div>\r\n");
        out.write("                            ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent(null);
    // /login.jsp(287,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty error}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                                <div class=\"error-message\">\r\n");
        out.write("                                    ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\r\n");
        out.write("                                </div>\r\n");
        out.write("                            ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }
}
