/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.11
 * Generated at: 2025-10-20 05:10:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class news_002dadd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1760802865264L));
    _jspx_dependants.put("jar:file:/H:/web_abcnew_asignment/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/abc_new/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664428278000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Thêm tin tức mới - ABC News Admin</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Header */\r\n");
      out.write("        .header {\r\n");
      out.write("            background: linear-gradient(135deg, #c41e3a 0%, #a01729 100%);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 15px 0;\r\n");
      out.write("            box-shadow: 0 2px 10px rgba(0,0,0,0.1);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .header .container {\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 0 20px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .logo {\r\n");
      out.write("            font-size: 1.8rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .user-info {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .user-info span {\r\n");
      out.write("            background: rgba(255,255,255,0.2);\r\n");
      out.write("            padding: 8px 15px;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .logout-btn {\r\n");
      out.write("            background: rgba(255,255,255,0.2);\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 8px 15px;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            transition: all 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .logout-btn:hover {\r\n");
      out.write("            background: rgba(255,255,255,0.3);\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Main Layout */\r\n");
      out.write("        .main-layout {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: 250px 1fr;\r\n");
      out.write("            min-height: calc(100vh - 70px);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Sidebar */\r\n");
      out.write("        .sidebar {\r\n");
      out.write("            background: white;\r\n");
      out.write("            box-shadow: 2px 0 10px rgba(0,0,0,0.1);\r\n");
      out.write("            padding: 20px 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .sidebar-menu {\r\n");
      out.write("            list-style: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .sidebar-menu li {\r\n");
      out.write("            margin-bottom: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .sidebar-menu a {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 12px;\r\n");
      out.write("            padding: 15px 20px;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            transition: all 0.3s;\r\n");
      out.write("            border-left: 3px solid transparent;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .sidebar-menu a:hover,\r\n");
      out.write("        .sidebar-menu a.active {\r\n");
      out.write("            background: #f8f9fa;\r\n");
      out.write("            border-left-color: #c41e3a;\r\n");
      out.write("            color: #c41e3a;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .sidebar-menu .icon {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            width: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Content */\r\n");
      out.write("        .content {\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .page-header {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .page-title {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .back-btn {\r\n");
      out.write("            background: #6c757d;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            transition: all 0.3s;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 8px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .back-btn:hover {\r\n");
      out.write("            background: #5a6268;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Form Container */\r\n");
      out.write("        .form-container {\r\n");
      out.write("            background: white;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 2px 10px rgba(0,0,0,0.1);\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: 2fr 1fr;\r\n");
      out.write("            gap: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-group {\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin-bottom: 8px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-input,\r\n");
      out.write("        .form-select,\r\n");
      out.write("        .form-textarea {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 12px 15px;\r\n");
      out.write("            border: 1px solid #ddd;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            transition: all 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-input:focus,\r\n");
      out.write("        .form-select:focus,\r\n");
      out.write("        .form-textarea:focus {\r\n");
      out.write("            outline: none;\r\n");
      out.write("            border-color: #c41e3a;\r\n");
      out.write("            box-shadow: 0 0 0 3px rgba(196, 30, 58, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-textarea {\r\n");
      out.write("            resize: vertical;\r\n");
      out.write("            min-height: 120px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-textarea.content {\r\n");
      out.write("            min-height: 300px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .file-input-wrapper {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .file-input {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .file-input-display {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("            padding: 12px 15px;\r\n");
      out.write("            border: 2px dashed #ddd;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            background: #f8f9fa;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .file-input-display:hover {\r\n");
      out.write("            border-color: #c41e3a;\r\n");
      out.write("            background: #fff5f5;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .image-preview {\r\n");
      out.write("            max-width: 100%;\r\n");
      out.write("            max-height: 200px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .checkbox-group {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .checkbox {\r\n");
      out.write("            width: 18px;\r\n");
      out.write("            height: 18px;\r\n");
      out.write("            accent-color: #c41e3a;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Form Actions */\r\n");
      out.write("        .form-actions {\r\n");
      out.write("            grid-column: 1 / -1;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 15px;\r\n");
      out.write("            justify-content: flex-end;\r\n");
      out.write("            margin-top: 30px;\r\n");
      out.write("            padding-top: 20px;\r\n");
      out.write("            border-top: 1px solid #f0f0f0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn {\r\n");
      out.write("            padding: 12px 24px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 8px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-primary {\r\n");
      out.write("            background: linear-gradient(135deg, #c41e3a, #a01729);\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-primary:hover {\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 5px 15px rgba(196, 30, 58, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-secondary {\r\n");
      out.write("            background: #6c757d;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-secondary:hover {\r\n");
      out.write("            background: #5a6268;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-success {\r\n");
      out.write("            background: #28a745;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-success:hover {\r\n");
      out.write("            background: #218838;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Alert Messages */\r\n");
      out.write("        .alert {\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .alert-error {\r\n");
      out.write("            background: #f8d7da;\r\n");
      out.write("            color: #721c24;\r\n");
      out.write("            border: 1px solid #f5c6cb;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Side Panel */\r\n");
      out.write("        .side-panel {\r\n");
      out.write("            background: #f8f9fa;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            height: fit-content;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .side-panel h3 {\r\n");
      out.write("            color: #333;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .help-text {\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            color: #666;\r\n");
      out.write("            line-height: 1.5;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .tips-list {\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .tips-list li {\r\n");
      out.write("            margin-bottom: 8px;\r\n");
      out.write("            color: #666;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: flex-start;\r\n");
      out.write("            gap: 8px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        /* Responsive */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .main-layout {\r\n");
      out.write("                grid-template-columns: 1fr;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .sidebar {\r\n");
      out.write("                display: none;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .form-grid {\r\n");
      out.write("                grid-template-columns: 1fr;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .form-actions {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <header class=\"header\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/dashboard\" class=\"logo\">\r\n");
      out.write("                🛡️ ABC NEWS ADMIN\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"user-info\">\r\n");
      out.write("                <span>👤 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username != null ? sessionScope.username : 'Admin'}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\" class=\"logout-btn\">\r\n");
      out.write("                    🚪 Đăng xuất\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"main-layout\">\r\n");
      out.write("        <!-- Sidebar -->\r\n");
      out.write("        <nav class=\"sidebar\">\r\n");
      out.write("            <ul class=\"sidebar-menu\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/dashboard\">\r\n");
      out.write("                        <span class=\"icon\">📊</span>\r\n");
      out.write("                        <span>Tổng quan</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/users\">\r\n");
      out.write("                        <span class=\"icon\">👥</span>\r\n");
      out.write("                        <span>Quản lý người dùng</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/categories\">\r\n");
      out.write("                        <span class=\"icon\">📂</span>\r\n");
      out.write("                        <span>Quản lý danh mục</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/news\" class=\"active\">\r\n");
      out.write("                        <span class=\"icon\">📰</span>\r\n");
      out.write("                        <span>Quản lý tin tức</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/newsletters\">\r\n");
      out.write("                        <span class=\"icon\">📧</span>\r\n");
      out.write("                        <span>Quản lý Newsletter</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/home\">\r\n");
      out.write("                        <span class=\"icon\">🏠</span>\r\n");
      out.write("                        <span>Xem trang chủ</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("        <!-- Main Content -->\r\n");
      out.write("        <main class=\"content\">\r\n");
      out.write("            <!-- Page Header -->\r\n");
      out.write("            <div class=\"page-header\">\r\n");
      out.write("                <h1 class=\"page-title\">➕ Thêm tin tức mới</h1>\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/news\" class=\"back-btn\">\r\n");
      out.write("                    <span>←</span>\r\n");
      out.write("                    <span>Quay lại danh sách</span>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Error Messages -->\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <!-- Form Container -->\r\n");
      out.write("            <div class=\"form-container\">\r\n");
      out.write("                <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/news/add\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("                    <div class=\"form-grid\">\r\n");
      out.write("                        <!-- Main Form -->\r\n");
      out.write("                        <div class=\"main-form\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"title\" class=\"form-label\">Tiêu đề tin tức *</label>\r\n");
      out.write("                                <input type=\"text\" id=\"title\" name=\"title\" class=\"form-input\" \r\n");
      out.write("                                       value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.title}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required \r\n");
      out.write("                                       placeholder=\"Nhập tiêu đề tin tức...\">\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"summary\" class=\"form-label\">Tóm tắt *</label>\r\n");
      out.write("                                <textarea id=\"summary\" name=\"summary\" class=\"form-textarea\" \r\n");
      out.write("                                          required placeholder=\"Nhập tóm tắt ngắn gọn về tin tức...\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.summary}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"content\" class=\"form-label\">Nội dung tin tức *</label>\r\n");
      out.write("                                <textarea id=\"content\" name=\"content\" class=\"form-textarea content\" \r\n");
      out.write("                                          required placeholder=\"Nhập nội dung chi tiết của tin tức...\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.content}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"imageFile\" class=\"form-label\">Hình ảnh đại diện</label>\r\n");
      out.write("                                <div class=\"file-input-wrapper\">\r\n");
      out.write("                                    <input type=\"file\" id=\"imageFile\" name=\"imageFile\" class=\"file-input\" \r\n");
      out.write("                                           accept=\"image/*\" onchange=\"previewImage(this)\">\r\n");
      out.write("                                    <div class=\"file-input-display\">\r\n");
      out.write("                                        <span>📷</span>\r\n");
      out.write("                                        <span>Chọn hình ảnh hoặc kéo thả vào đây</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <img id=\"imagePreview\" class=\"image-preview\" alt=\"Preview\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Side Panel -->\r\n");
      out.write("                        <div class=\"side-panel\">\r\n");
      out.write("                            <h3>📋 Thông tin xuất bản</h3>\r\n");
      out.write("                            \r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label for=\"categoryId\" class=\"form-label\">Danh mục *</label>\r\n");
      out.write("                                <select id=\"categoryId\" name=\"categoryId\" class=\"form-select\" required>\r\n");
      out.write("                                    <option value=\"\">Chọn danh mục</option>\r\n");
      out.write("                                    ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <div class=\"checkbox-group\">\r\n");
      out.write("                                    <input type=\"checkbox\" id=\"published\" name=\"published\" \r\n");
      out.write("                                           value=\"1\" class=\"checkbox\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.published == '1' ? 'checked' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("                                    <label for=\"published\" class=\"form-label\">Xuất bản ngay</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"help-text\">\r\n");
      out.write("                                <strong>💡 Gợi ý:</strong>\r\n");
      out.write("                                <ul class=\"tips-list\">\r\n");
      out.write("                                    <li>📝 Tiêu đề nên ngắn gọn, súc tích</li>\r\n");
      out.write("                                    <li>📄 Tóm tắt không quá 200 từ</li>\r\n");
      out.write("                                    <li>🖼️ Hình ảnh nên có kích thước 800x600px</li>\r\n");
      out.write("                                    <li>✅ Kiểm tra chính tả trước khi đăng</li>\r\n");
      out.write("                                    <li>🔍 Sử dụng từ khóa phù hợp</li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Form Actions -->\r\n");
      out.write("                        <div class=\"form-actions\">\r\n");
      out.write("                            <button type=\"submit\" name=\"action\" value=\"draft\" class=\"btn btn-secondary\">\r\n");
      out.write("                                <span>💾</span>\r\n");
      out.write("                                <span>Lưu bản nháp</span>\r\n");
      out.write("                            </button>\r\n");
      out.write("                            <button type=\"submit\" name=\"action\" value=\"publish\" class=\"btn btn-primary\">\r\n");
      out.write("                                <span>🚀</span>\r\n");
      out.write("                                <span>Đăng tin tức</span>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </main>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function previewImage(input) {\r\n");
      out.write("            const preview = document.getElementById('imagePreview');\r\n");
      out.write("            const display = input.parentElement.querySelector('.file-input-display span:last-child');\r\n");
      out.write("            \r\n");
      out.write("            if (input.files && input.files[0]) {\r\n");
      out.write("                const reader = new FileReader();\r\n");
      out.write("                \r\n");
      out.write("                reader.onload = function(e) {\r\n");
      out.write("                    preview.src = e.target.result;\r\n");
      out.write("                    preview.style.display = 'block';\r\n");
      out.write("                    display.textContent = input.files[0].name;\r\n");
      out.write("                };\r\n");
      out.write("                \r\n");
      out.write("                reader.readAsDataURL(input.files[0]);\r\n");
      out.write("            } else {\r\n");
      out.write("                preview.style.display = 'none';\r\n");
      out.write("                display.textContent = 'Chọn hình ảnh hoặc kéo thả vào đây';\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Auto-save draft every 2 minutes\r\n");
      out.write("        let autoSaveInterval;\r\n");
      out.write("        \r\n");
      out.write("        function startAutoSave() {\r\n");
      out.write("            autoSaveInterval = setInterval(function() {\r\n");
      out.write("                const title = document.getElementById('title').value;\r\n");
      out.write("                const summary = document.getElementById('summary').value;\r\n");
      out.write("                const content = document.getElementById('content').value;\r\n");
      out.write("                \r\n");
      out.write("                if (title || summary || content) {\r\n");
      out.write("                    // Save to localStorage as backup\r\n");
      out.write("                    localStorage.setItem('news_draft', JSON.stringify({\r\n");
      out.write("                        title: title,\r\n");
      out.write("                        summary: summary,\r\n");
      out.write("                        content: content,\r\n");
      out.write("                        timestamp: new Date().toISOString()\r\n");
      out.write("                    }));\r\n");
      out.write("                    console.log('Đã tự động lưu bản nháp');\r\n");
      out.write("                }\r\n");
      out.write("            }, 120000); // 2 minutes\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Load draft from localStorage\r\n");
      out.write("        function loadDraft() {\r\n");
      out.write("            const draft = localStorage.getItem('news_draft');\r\n");
      out.write("            if (draft) {\r\n");
      out.write("                const data = JSON.parse(draft);\r\n");
      out.write("                const now = new Date();\r\n");
      out.write("                const draftTime = new Date(data.timestamp);\r\n");
      out.write("                const diffHours = (now - draftTime) / (1000 * 60 * 60);\r\n");
      out.write("                \r\n");
      out.write("                // Only load if draft is less than 24 hours old\r\n");
      out.write("                if (diffHours < 24) {\r\n");
      out.write("                    if (confirm('Tìm thấy bản nháp đã lưu từ ' + draftTime.toLocaleString() + '. Bạn có muốn khôi phục không?')) {\r\n");
      out.write("                        document.getElementById('title').value = data.title || '';\r\n");
      out.write("                        document.getElementById('summary').value = data.summary || '';\r\n");
      out.write("                        document.getElementById('content').value = data.content || '';\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Clear draft after successful submission\r\n");
      out.write("        function clearDraft() {\r\n");
      out.write("            localStorage.removeItem('news_draft');\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Initialize\r\n");
      out.write("        document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("            loadDraft();\r\n");
      out.write("            startAutoSave();\r\n");
      out.write("            \r\n");
      out.write("            // Clear draft on form submission\r\n");
      out.write("            document.querySelector('form').addEventListener('submit', function() {\r\n");
      out.write("                clearDraft();\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Character counter for summary\r\n");
      out.write("        document.getElementById('summary').addEventListener('input', function() {\r\n");
      out.write("            const maxLength = 500;\r\n");
      out.write("            const currentLength = this.value.length;\r\n");
      out.write("            \r\n");
      out.write("            // You can add a character counter display here\r\n");
      out.write("            if (currentLength > maxLength) {\r\n");
      out.write("                this.style.borderColor = '#dc3545';\r\n");
      out.write("            } else {\r\n");
      out.write("                this.style.borderColor = '#ddd';\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /views/admin/news-add.jsp(453,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty error}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                <div class=\"alert alert-error\">\r\n");
        out.write("                    ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\r\n");
        out.write("                </div>\r\n");
        out.write("            ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /views/admin/news-add.jsp(506,36) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("category");
    // /views/admin/news-add.jsp(506,36) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/views/admin/news-add.jsp(506,36) '${categories}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${categories}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                                        <option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" \r\n");
          out.write("                                                ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.categoryId == category.id ? 'selected' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(">\r\n");
          out.write("                                            ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\r\n");
          out.write("                                        </option>\r\n");
          out.write("                                    ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    return false;
  }
}
