/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.11
 * Generated at: 2025-10-19 17:23:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class user_002dadd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1760802865264L));
    _jspx_dependants.put("jar:file:/H:/web_abcnew_asignment/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/abc_new/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664428278000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Thêm người dùng - ABC News Admin</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("            background-color: #f8f9fa;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .header {\r\n");
      out.write("            background: linear-gradient(135deg, #c41e3a 0%, #a01729 100%);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 15px 0;\r\n");
      out.write("            box-shadow: 0 2px 10px rgba(0,0,0,0.1);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .header .container {\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 0 20px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .logo {\r\n");
      out.write("            font-size: 1.8rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .user-info {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .user-info span {\r\n");
      out.write("            background: rgba(255,255,255,0.2);\r\n");
      out.write("            padding: 8px 15px;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .logout-btn {\r\n");
      out.write("            background: rgba(255,255,255,0.2);\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 8px 15px;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            transition: all 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .logout-btn:hover {\r\n");
      out.write("            background: rgba(255,255,255,0.3);\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 800px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            padding: 30px 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .page-header {\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .page-title {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .page-subtitle {\r\n");
      out.write("            color: #666;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .back-btn {\r\n");
      out.write("            background: #6c757d;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 6px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            transition: all 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .back-btn:hover {\r\n");
      out.write("            background: #5a6268;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .alert {\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .alert-error {\r\n");
      out.write("            background: #f8d7da;\r\n");
      out.write("            color: #721c24;\r\n");
      out.write("            border: 1px solid #f5c6cb;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-container {\r\n");
      out.write("            background: white;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 5px 15px rgba(0,0,0,0.1);\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: 1fr 1fr;\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-group {\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-group.full-width {\r\n");
      out.write("            grid-column: 1 / -1;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-group label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin-bottom: 8px;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            color: #333;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .required {\r\n");
      out.write("            color: #dc3545;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-group input,\r\n");
      out.write("        .form-group select {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 12px 15px;\r\n");
      out.write("            border: 2px solid #e0e0e0;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            transition: border-color 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-group input:focus,\r\n");
      out.write("        .form-group select:focus {\r\n");
      out.write("            outline: none;\r\n");
      out.write("            border-color: #c41e3a;\r\n");
      out.write("            box-shadow: 0 0 0 3px rgba(196, 30, 58, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-actions {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 15px;\r\n");
      out.write("            justify-content: flex-end;\r\n");
      out.write("            margin-top: 30px;\r\n");
      out.write("            padding-top: 20px;\r\n");
      out.write("            border-top: 1px solid #f0f0f0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn {\r\n");
      out.write("            padding: 12px 24px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            transition: all 0.3s;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-primary {\r\n");
      out.write("            background: linear-gradient(135deg, #c41e3a, #a01729);\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-primary:hover {\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("            box-shadow: 0 5px 15px rgba(196, 30, 58, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-secondary {\r\n");
      out.write("            background: #6c757d;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .btn-secondary:hover {\r\n");
      out.write("            background: #5a6268;\r\n");
      out.write("            color: white;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .form-help {\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            color: #666;\r\n");
      out.write("            margin-top: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .form-grid {\r\n");
      out.write("                grid-template-columns: 1fr;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .form-actions {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <header class=\"header\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/dashboard\" class=\"logo\">\r\n");
      out.write("                🛡️ ABC NEWS ADMIN\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"user-info\">\r\n");
      out.write("                <span>👤 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username != null ? sessionScope.username : 'Admin'}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\" class=\"logout-btn\">\r\n");
      out.write("                    🚪 Đăng xuất\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/users\" class=\"back-btn\">\r\n");
      out.write("            ← Quay lại danh sách\r\n");
      out.write("        </a>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Page Header -->\r\n");
      out.write("        <div class=\"page-header\">\r\n");
      out.write("            <h1 class=\"page-title\">➕ Thêm người dùng mới</h1>\r\n");
      out.write("            <p class=\"page-subtitle\">Điền thông tin để tạo tài khoản người dùng mới</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Error Message -->\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Add User Form -->\r\n");
      out.write("        <div class=\"form-container\">\r\n");
      out.write("            <form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/users/add\">\r\n");
      out.write("                <div class=\"form-grid\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"id\">ID người dùng <span class=\"required\">*</span></label>\r\n");
      out.write("                        <input type=\"text\" id=\"id\" name=\"id\" required \r\n");
      out.write("                               value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Nhập ID (vd: admin, pv001)\">\r\n");
      out.write("                        <div class=\"form-help\">ID duy nhất, không thể thay đổi sau khi tạo</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"password\">Mật khẩu <span class=\"required\">*</span></label>\r\n");
      out.write("                        <input type=\"password\" id=\"password\" name=\"password\" required \r\n");
      out.write("                               placeholder=\"Nhập mật khẩu\">\r\n");
      out.write("                        <div class=\"form-help\">Tối thiểu 6 ký tự</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group full-width\">\r\n");
      out.write("                        <label for=\"fullname\">Họ và tên <span class=\"required\">*</span></label>\r\n");
      out.write("                        <input type=\"text\" id=\"fullname\" name=\"fullname\" required \r\n");
      out.write("                               value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.fullname}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Nhập họ và tên đầy đủ\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"email\">Email</label>\r\n");
      out.write("                        <input type=\"email\" id=\"email\" name=\"email\" \r\n");
      out.write("                               value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.email}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Nhập địa chỉ email\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"mobile\">Số điện thoại</label>\r\n");
      out.write("                        <input type=\"tel\" id=\"mobile\" name=\"mobile\" \r\n");
      out.write("                               value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.mobile}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Nhập số điện thoại\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"birthday\">Ngày sinh</label>\r\n");
      out.write("                        <input type=\"date\" id=\"birthday\" name=\"birthday\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.birthday}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"gender\">Giới tính</label>\r\n");
      out.write("                        <select id=\"gender\" name=\"gender\">\r\n");
      out.write("                            <option value=\"\">-- Chọn giới tính --</option>\r\n");
      out.write("                            <option value=\"1\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.gender == '1' ? 'selected' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Nam</option>\r\n");
      out.write("                            <option value=\"0\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.gender == '0' ? 'selected' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Nữ</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"role\">Vai trò <span class=\"required\">*</span></label>\r\n");
      out.write("                        <select id=\"role\" name=\"role\" required>\r\n");
      out.write("                            <option value=\"\">-- Chọn vai trò --</option>\r\n");
      out.write("                            <option value=\"1\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.role == '1' ? 'selected' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">🛡️ Quản trị viên</option>\r\n");
      out.write("                            <option value=\"0\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.role == '0' ? 'selected' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">✍️ Phóng viên</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        <div class=\"form-help\">Quản trị viên có quyền quản lý toàn bộ hệ thống</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"form-actions\">\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/users\" class=\"btn btn-secondary\">\r\n");
      out.write("                        ❌ Hủy bỏ\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">\r\n");
      out.write("                        ✅ Thêm người dùng\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        // Auto generate ID from fullname\r\n");
      out.write("        document.getElementById('fullname').addEventListener('input', function() {\r\n");
      out.write("            const fullname = this.value;\r\n");
      out.write("            const idField = document.getElementById('id');\r\n");
      out.write("            \r\n");
      out.write("            if (fullname && !idField.value) {\r\n");
      out.write("                // Simple ID generation (you can improve this)\r\n");
      out.write("                const words = fullname.toLowerCase().split(' ');\r\n");
      out.write("                let suggestedId = '';\r\n");
      out.write("                \r\n");
      out.write("                if (words.length >= 2) {\r\n");
      out.write("                    suggestedId = words[words.length - 1] + words[0].charAt(0);\r\n");
      out.write("                } else {\r\n");
      out.write("                    suggestedId = words[0];\r\n");
      out.write("                }\r\n");
      out.write("                \r\n");
      out.write("                // Remove Vietnamese accents and special characters\r\n");
      out.write("                suggestedId = suggestedId.normalize('NFD').replace(/[\\u0300-\\u036f]/g, '');\r\n");
      out.write("                suggestedId = suggestedId.replace(/[^a-z0-9]/g, '');\r\n");
      out.write("                \r\n");
      out.write("                idField.placeholder = 'Gợi ý: ' + suggestedId;\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // Form validation\r\n");
      out.write("        document.querySelector('form').addEventListener('submit', function(e) {\r\n");
      out.write("            const id = document.getElementById('id').value.trim();\r\n");
      out.write("            const password = document.getElementById('password').value;\r\n");
      out.write("            const fullname = document.getElementById('fullname').value.trim();\r\n");
      out.write("            const role = document.getElementById('role').value;\r\n");
      out.write("            \r\n");
      out.write("            if (!id || !password || !fullname || !role) {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                alert('Vui lòng điền đầy đủ các trường bắt buộc!');\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            if (password.length < 6) {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                alert('Mật khẩu phải có ít nhất 6 ký tự!');\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            if (!/^[a-zA-Z0-9_]+$/.test(id)) {\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                alert('ID chỉ được chứa chữ cái, số và dấu gạch dưới!');\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /views/admin/user-add.jsp(262,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty error}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("            <div class=\"alert alert-error\">\r\n");
        out.write("                ❌ ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\r\n");
        out.write("            </div>\r\n");
        out.write("        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
